services:
  web:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - ./src:/app
    environment:
      - FLASK_ENV=production
      - DATABASE_URL=sqlite:///produtos.db
    restart: always